# Generated by Django 2.1.4 on 2019-02-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='producs',
            new_name='products',
        ),
    ]
