# Generated by Django 2.1.4 on 2019-01-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190125_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featued',
            new_name='featured',
        ),
    ]
