# Generated by Django 2.1.4 on 2019-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190125_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
